name: ci action

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - name: initialization
        run: echo "initialize"

      - uses: actions/checkout@v3

      - name: setup java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: test java version
        run: java -version

      # - name: build with maven
      #   run: mvn --file ics/pom.xml clean install -DskipTests

      - name: Test with Maven
        working-directory: ics
        run: mvn --file pom.xml test
